
###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$rofi = ~/.config/rofi/launchers/type-2/launcher.sh
$firefox = firefox
$code = nvim

exec-once = swww-daemon
exec-once = ~/.config/hypr/scripts/wallpaper.sh
exec-once = waybar
exec-once = swaync
exec-once = xsettingsd

env = XCURSOR_THEME, Adwaita
env = XCURSOR_SIZE,20
env = HYPRCURSOR_THEME, Adwaita
env = HYPRCURSOR_SIZE,20

#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(aaaaaa99)
    col.inactive_border = rgba(66666644)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 4
    rounding_power = 1

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    animate_manual_resizes = false
    focus_on_activate = true
}

input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    repeat_delay = 150
    repeat_rate = 60

    follow_mouse = 1
    accel_profile = flat
    sensitivity = 0
    force_no_accel = true

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = 0
}

source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/monitors.conf
