
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# See https://wiki.hypr.land/Configuring/Monitors/

monitor=eDP-1,1920x1200@60,0x103,1.25

workspace=1, monitor:eDP-1 (ID 0), persistent:true
workspace=2, monitor:eDP-1 (ID 0), persistent:true
workspace=3, monitor:eDP-1 (ID 0), persistent:true
workspace=4, monitor:eDP-1 (ID 0), persistent:true 
workspace=5, monitor:eDP-1 (ID 0), persistent:true

