local opt = vim.opt
opt.mouse = "a"
opt.tabstop = 4
opt.shiftwidth = 4
opt.softtabstop = 4
opt.expandtab = true
opt.autoindent = true
opt.smartindent = true
opt.relativenumber = false
opt.number = true
opt.scrolloff = 8
opt.wrap = false
opt.signcolumn = "yes"
